esphome:
name: PlatformIO CI
  platform: ESP8266
  board: d1_mini
  framework:
    type: arduino
  
on: push
    
jobs:
  main:
    name: Main
    #runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: '3.x'
      - name: Install Platform IO
        run: |
          python -m pip install --upgrade pip
          pip install -U platformio
      - name: Build
        run: platformio run
